FROM espressif/idf:latest
RUN apt-get install -y git
RUN cd /opt/esp/
RUN git clone --recursive https://github.com/espressif/esp-mdf.git
export MDF_PATH="/opt/esp/esp-mdf"
cp -rf /opt/esp/esp-mdf/examples/get-started /home/workdir/
export CXX="/opt/esp/idf/tools/cmake"
apt install avahi-utils
idf.py add-dependency espressif/mdns==1.0.3
idf.py add-dependency espressif/coap

